CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR2(255) UNIQUE NOT NULL,
  username VARCHAR2(100) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  confirmPassword TEXT NOT NULL,
  role VARCHAR2(50) DEFAULT 'user'
);
