- name: Déploiement de la plateforme hybride
  hosts: auth_app
  become: true
  roles:
    - docker
    - database
    - backend
    - frontend
    - sonarqube
  tasks:

    - name: Installer unzip si nécessaire
      apt:
        name: unzip
        state: present

    - name: Créer l'utilisateur sonar
      user:
        name: sonar
        shell: /bin/bash
        create_home: yes

    - name: Télécharger SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
        dest: /tmp/sonarqube.zip

    - name: Décompresser SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes

    - name: Renommer le dossier
      command: mv /opt/sonarqube-9.9.0.65466 /opt/sonarqube
      args:
        creates: /opt/sonarqube

    - name: Changer le propriétaire des fichiers SonarQube
      file:
        path: /opt/sonarqube
        state: directory
        recurse: yes
        owner: sonar
        group: sonar

    - name: Configurer PostgreSQL dans SonarQube
      lineinfile:
        path: /opt/sonarqube/conf/sonar.properties
        regexp: '^#sonar.jdbc.url='
        line: sonar.jdbc.url=jdbc:postgresql://localhost:5432/auth_db
        state: present

    - name: Ajouter login PostgreSQL
      lineinfile:
        path: /opt/sonarqube/conf/sonar.properties
        regexp: '^#sonar.jdbc.username='
        line: sonar.jdbc.username=postgres

    - name: Ajouter mot de passe PostgreSQL
      lineinfile:
        path: /opt/sonarqube/conf/sonar.properties
        regexp: '^#sonar.jdbc.password='
        line: sonar.jdbc.password=mot_de_passe_postgres

    - name: Démarrer SonarQube
      command: /opt/sonarqube/bin/linux-x86-64/sonar.sh start
