{
 "title": "PFE - Monitoring Serveur (Node Exporter)",
 "tags": [
  "pfe",
  "node-exporter"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Utilisation CPU (%)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Utilisation Mémoire (MB)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Machine UP/DOWN",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Charge Moyenne (1min)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "node_load1" }
   ]
  }
 ]
}