---
- name: Installer SonarQube sur le serveur
  hosts: all
  become: yes
  tasks:
    - name: Installer Java (prérequis SonarQube)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Télécharger SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip
        dest: /tmp/sonarqube.zip

    - name: Décompresser SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt
        remote_src: yes

    - name: Créer un lien symbolique vers sonarqube
      file:
        src: /opt/sonarqube-10.4.1.88267
        dest: /opt/sonarqube
        state: link

    - name: Configurer SonarQube comme service systemd
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=network.target

          [Service]
          Type=forking
          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
          User=root
          Group=root
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Démarrer et activer SonarQube
      systemd:
        name: sonarqube
        enabled: yes
        state: started
